[project]
name = "project-scaffolder"
version = "0.1.0"
description = "CLI tool to initialize a modular data project"
authors = [{ name = "abdoul", email="mounkaila.issoufou025@gmail.com" }]
requires-python = ">=3.10"

readme = "README.md"

dependencies = [
  "click",
  "pyyaml"
]

[project.scripts]
project-scaffolder = "project_scaffolder.cli:main"


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# -----------------
# Black configuration
# -----------------
[tool.black]
line-length = 88
target-version = ["py310"]

# -----------------
# Ruff configuration
# -----------------
[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.pytest.ini_options]
testpaths = [
    "src/project_scaffolder/tests"
]
